In [ ]:
import os
import sys
import importlib
from google.colab import drive

if not os.path.exists('/content/drive/MyDrive'):
    drive.mount('/content/drive')
else:
    print("Drive già montato, salto il mount.")

sys.path.append('/content/drive/MyDrive/progetto_immunogold/scripts')
importlib.invalidate_caches()

import common
importlib.reload(common)
from common import *

print(f"Device attivo: {device}")
print(paths)
log('Notebook avviato correttamente')

Mounted at /content/drive
Device attivo: cpu
[2026-09-03 13:27] Notebook avviato

In [ ]:
print(paths)

{'raw_images': '/content/drive/MyDrive/progetto_immunogold/raw_images', 'annotations': '/content/drive/MyDrive/progetto_immunogold/annotations', 'patches_images': '/content/drive/MyDrive/progetto_immunogold/patches/images', 'patches_density': '/content/drive/MyDrive/progetto_immunogold/patches/density_maps', 'checkpoints': '/content/drive/MyDrive/progetto_immunogold/checkpoints', 'logs': '/content/drive/MyDrive/progetto_immunogold/logs'}

In [ ]:
import os
import pandas as pd

raw_root = paths['raw_images']

rows = []
for esperimento in sorted(os.listdir(raw_root)):
    esp_path = os.path.join(raw_root, esperimento)
    if not os.path.isdir(esp_path):
        continue
    for gruppo in sorted(os.listdir(esp_path)):
        gruppo_path = os.path.join(esp_path, gruppo)
        if not os.path.isdir(gruppo_path):
            continue
        for fname in sorted(os.listdir(gruppo_path)):
            if fname.lower().endswith(('.tif', '.tiff', '.png', '.jpg')):
                rows.append({
                    'filename': fname,
                    'filepath': os.path.join(esperimento, gruppo, fname),
                    'esperimento': esperimento,
                    'gruppo_ingrandimento': gruppo,
                    'nm_per_pixel': None,
                })

df = pd.DataFrame(rows)   # <-- aggiunta: costruisce df dalla lista rows

n_combinazioni = df.groupby(['esperimento', 'gruppo_ingrandimento']).ngroups
log(f'Trovate {len(df)} immagini in {n_combinazioni} combinazioni esperimento+gruppo distinte')

riepilogo = df.groupby(['esperimento', 'gruppo_ingrandimento']).size().reset_index(name='n_immagini')
print(riepilogo)
df.head()

[2026-09-03 13:27] Trovate 144 immagini in 24 combinazioni esperimento+gruppo distinte
                      esperimento gruppo_ingrandimento  n_immagini
0   06_08_26_U87KO_Immunogold_Ida       1000nm_gruppoA           1
1   06_08_26_U87KO_Immunogold_Ida        200nm_gruppoA          19
2   06_08_26_U87KO_Immunogold_Ida        200nm_gruppoB           2
3   06_08_26_U87KO_Immunogold_Ida        200nm_gruppoC           6
4   06_08_26_U87KO_Immunogold_Ida        500nm_gruppoA          11
5   06_08_26_U87KO_Immunogold_Ida        500nm_gruppoB           2
6   09_07_26_U87WT_Immunogold_Ida       1000nm_gruppoA           1
7   09_07_26_U87WT_Immunogold_Ida       1000nm_gruppoB           1
8   09_07_26_U87WT_Immunogold_Ida       2000nm_gruppoA           2
9   09_07_26_U87WT_Immunogold_Ida        200nm_gruppoA           3
10  09_07_26_U87WT_Immunogold_Ida        200nm_gruppoB           6
11  09_07_26_U87WT_Immunogold_Ida        200nm_gruppoC           3
12  09_07_26_U87WT_Immunogold_Ida        500nm_gruppoA           3
13  09_07_26_U87WT_Immunogold_Ida        500nm_gruppoB           3
14  09_07_26_U87WT_Immunogold_Ida        500nm_gruppoC           5
15  10_07_26_U87KO_Immunogold_Ida       1000nm_gruppoA           1
16  10_07_26_U87KO_Immunogold_Ida        500nm_gruppoA          12
17  10_07_26_U87KO_Immunogold_Ida        500nm_gruppoB           2
18  10_07_26_U87KO_Immunogold_Ida        500nm_gruppoC           3
19  28_07_26_U87WT_Immunogold_Ida        200nm_gruppoA          17
20  28_07_26_U87WT_Immunogold_Ida        200nm_gruppoB           9
21  28_07_26_U87WT_Immunogold_Ida        200nm_gruppoC           7
22  28_07_26_U87WT_Immunogold_Ida        500nm_gruppoA           1
23  28_07_26_U87WT_Immunogold_Ida        500nm_gruppoB          24

,filename,filepath,esperimento,gruppo_ingrandimento,nm_per_pixel
0,SA-MAG_X8000_JEM-1400 Flash_22612.jpg,06_08_26_U87KO_Immunogold_Ida/1000nm_gruppoA/S...,06_08_26_U87KO_Immunogold_Ida,1000nm_gruppoA,None
1,SA-MAG_X20k_JEM-1400 Flash_22614.jpg,06_08_26_U87KO_Immunogold_Ida/200nm_gruppoA/SA...,06_08_26_U87KO_Immunogold_Ida,200nm_gruppoA,None
2,SA-MAG_X20k_JEM-1400 Flash_22620.jpg,06_08_26_U87KO_Immunogold_Ida/200nm_gruppoA/SA...,06_08_26_U87KO_Immunogold_Ida,200nm_gruppoA,None
3,SA-MAG_X20k_JEM-1400 Flash_22621.jpg,06_08_26_U87KO_Immunogold_Ida/200nm_gruppoA/SA...,06_08_26_U87KO_Immunogold_Ida,200nm_gruppoA,None
4,SA-MAG_X20k_JEM-1400 Flash_22622.jpg,06_08_26_U87KO_Immunogold_Ida/200nm_gruppoA/SA...,06_08_26_U87KO_Immunogold_Ida,200nm_gruppoA,None

In [ ]:
misure = {
    ('06_08_26_U87KO_Immunogold_Ida', '1000nm_gruppoA'): 2.11,
    ('06_08_26_U87KO_Immunogold_Ida', '200nm_gruppoA'):  0.84,
    ('06_08_26_U87KO_Immunogold_Ida', '200nm_gruppoB'):  0.67,
    ('06_08_26_U87KO_Immunogold_Ida', '200nm_gruppoC'):  0.56,
    ('06_08_26_U87KO_Immunogold_Ida', '500nm_gruppoA'):  1.12,
    ('06_08_26_U87KO_Immunogold_Ida', '500nm_gruppoB'):  1.68,
    ('09_07_26_U87WT_Immunogold_Ida', '1000nm_gruppoA'): 2.11,
    ('09_07_26_U87WT_Immunogold_Ida', '1000nm_gruppoB'): 2.82,
    ('09_07_26_U87WT_Immunogold_Ida', '2000nm_gruppoA'): 5.63,
    ('09_07_26_U87WT_Immunogold_Ida', '200nm_gruppoA'):  0.85,
    ('09_07_26_U87WT_Immunogold_Ida', '200nm_gruppoB'):  0.67,
    ('09_07_26_U87WT_Immunogold_Ida', '200nm_gruppoC'):  0.56,
    ('09_07_26_U87WT_Immunogold_Ida', '500nm_gruppoA'):  1.67,
    ('09_07_26_U87WT_Immunogold_Ida', '500nm_gruppoB'):  1.40,
    ('09_07_26_U87WT_Immunogold_Ida', '500nm_gruppoC'):  1.13,
    ('10_07_26_U87KO_Immunogold_Ida', '1000nm_gruppoA'): 2.82,
    ('10_07_26_U87KO_Immunogold_Ida', '500nm_gruppoA'):  1.69,
    ('10_07_26_U87KO_Immunogold_Ida', '500nm_gruppoB'):  1.41,
    ('10_07_26_U87KO_Immunogold_Ida', '500nm_gruppoC'):  1.13,
    ('28_07_26_U87WT_Immunogold_Ida', '200nm_gruppoA'):  0.84,
    ('28_07_26_U87WT_Immunogold_Ida', '200nm_gruppoB'):  0.67,
    ('28_07_26_U87WT_Immunogold_Ida', '200nm_gruppoC'):  0.45,
    ('28_07_26_U87WT_Immunogold_Ida', '500nm_gruppoA'):  1.41,
    ('28_07_26_U87WT_Immunogold_Ida', '500nm_gruppoB'):  1.13,
}

df['nm_per_pixel'] = df.apply(
    lambda r: misure.get((r['esperimento'], r['gruppo_ingrandimento'])), axis=1
)

csv_path = os.path.join(paths['annotations'], 'calibrazione.csv')
df.to_csv(csv_path, index=False)
log('calibrazione.csv salvato con tutte le calibrazioni assegnate')

[2026-09-03 13:27] calibrazione.csv salvato con tutte le calibrazioni assegnate

In [ ]:
mancanti = df[df['nm_per_pixel'].isna()]
if len(mancanti) > 0:
    print(f"Attenzione: {len(mancanti)} immagini senza calibrazione assegnata")
    print(mancanti[['esperimento', 'gruppo_ingrandimento']].drop_duplicates())
else:
    print("Tutte le immagini hanno una calibrazione assegnata correttamente.")
    print(df.groupby(['esperimento', 'gruppo_ingrandimento'])['nm_per_pixel'].first())

Tutte le immagini hanno una calibrazione assegnata correttamente.
esperimento                    gruppo_ingrandimento
06_08_26_U87KO_Immunogold_Ida  1000nm_gruppoA          2.11
                               200nm_gruppoA           0.84
                               200nm_gruppoB           0.67
                               200nm_gruppoC           0.56
                               500nm_gruppoA           1.12
                               500nm_gruppoB           1.68
09_07_26_U87WT_Immunogold_Ida  1000nm_gruppoA          2.11
                               1000nm_gruppoB          2.82
                               2000nm_gruppoA          5.63
                               200nm_gruppoA           0.85
                               200nm_gruppoB           0.67
                               200nm_gruppoC           0.56
                               500nm_gruppoA           1.67
                               500nm_gruppoB           1.40
                               500nm_gruppoC           1.13
10_07_26_U87KO_Immunogold_Ida  1000nm_gruppoA          2.82
                               500nm_gruppoA           1.69
                               500nm_gruppoB           1.41
                               500nm_gruppoC           1.13
28_07_26_U87WT_Immunogold_Ida  200nm_gruppoA           0.84
                               200nm_gruppoB           0.67
                               200nm_gruppoC           0.45
                               500nm_gruppoA           1.41
                               500nm_gruppoB           1.13
Name: nm_per_pixel, dtype: float64

In [ ]:
# per ogni etichetta di gruppo, mostra a quali esperimenti appartiene e con che nm_per_pixel
df.groupby(['gruppo_ingrandimento', 'esperimento'])['nm_per_pixel'].first().unstack()

esperimento,06_08_26_U87KO_Immunogold_Ida,09_07_26_U87WT_Immunogold_Ida,10_07_26_U87KO_Immunogold_Ida,28_07_26_U87WT_Immunogold_Ida
gruppo_ingrandimento,,,,
1000nm_gruppoA,2.11,2.11,2.82,NaN
1000nm_gruppoB,NaN,2.82,NaN,NaN
2000nm_gruppoA,NaN,5.63,NaN,NaN
200nm_gruppoA,0.84,0.85,NaN,0.84
200nm_gruppoB,0.67,0.67,NaN,0.67
200nm_gruppoC,0.56,0.56,NaN,0.45
500nm_gruppoA,1.12,1.67,1.69,1.41
500nm_gruppoB,1.68,1.40,1.41,1.13
500nm_gruppoC,NaN,1.13,1.13,NaN

In [ ]:
import numpy as np

tolleranza_relativa = 0.03  # 3% di differenza massima per considerare due misure "la stessa calibrazione"

valori_unici = sorted(set(misure.values()))

clusters = []
current_cluster = [valori_unici[0]]
for v in valori_unici[1:]:
    if (v - current_cluster[-1]) / current_cluster[-1] <= tolleranza_relativa:
        current_cluster.append(v)
    else:
        clusters.append(current_cluster)
        current_cluster = [v]
clusters.append(current_cluster)

cluster_map = {}
for i, cluster in enumerate(clusters):
    media = np.mean(cluster)
    label = f'classe_{i+1}'
    for v in cluster:
        cluster_map[v] = (label, media)

print(f"Da {len(misure)} combinazioni esperimento-gruppo, individuate {len(clusters)} classi di calibrazione reali:")
for i, cluster in enumerate(clusters):
    print(f"  classe_{i+1}: valori originali {cluster} -> media {np.mean(cluster):.3f} nm/px")

Da 24 combinazioni esperimento-gruppo, individuate 10 classi di calibrazione reali:
  classe_1: valori originali [0.45] -> media 0.450 nm/px
  classe_2: valori originali [0.56] -> media 0.560 nm/px
  classe_3: valori originali [0.67] -> media 0.670 nm/px
  classe_4: valori originali [0.84, 0.85] -> media 0.845 nm/px
  classe_5: valori originali [1.12, 1.13] -> media 1.125 nm/px
  classe_6: valori originali [1.4, 1.41] -> media 1.405 nm/px
  classe_7: valori originali [1.67, 1.68, 1.69] -> media 1.680 nm/px
  classe_8: valori originali [2.11] -> media 2.110 nm/px
  classe_9: valori originali [2.82] -> media 2.820 nm/px
  classe_10: valori originali [5.63] -> media 5.630 nm/px

In [ ]:
misure_classe = {k: cluster_map[v][0] for k, v in misure.items()}
misure_valore_finale = {k: cluster_map[v][1] for k, v in misure.items()}

df['classe_calibrazione'] = df.apply(
    lambda r: misure_classe.get((r['esperimento'], r['gruppo_ingrandimento'])), axis=1
)
df['nm_per_pixel'] = df.apply(
    lambda r: misure_valore_finale.get((r['esperimento'], r['gruppo_ingrandimento'])), axis=1
)

csv_path = os.path.join(paths['annotations'], 'calibrazione.csv')
df.to_csv(csv_path, index=False)
log('calibrazione.csv aggiornato con classi di calibrazione reali (indipendenti dall\'esperimento)')

df.groupby('classe_calibrazione')['nm_per_pixel'].agg(['mean', 'count'])

[2026-09-03 13:53] calibrazione.csv aggiornato con classi di calibrazione reali (indipendenti dall'esperimento)

                      mean  count
classe_calibrazione
classe_1             0.450      7
classe_10            5.630      2
classe_2             0.560      9
classe_3             0.670     17
classe_4             0.845     39
classe_5             1.125     43
classe_6             1.405      6
classe_7             1.680     17
classe_8             2.110      2
classe_9             2.820      2

In [ ]:
riepilogo_classi = df.groupby('classe_calibrazione').agg(
    n_immagini=('filename', 'count'),
    nm_per_pixel=('nm_per_pixel', 'first'),
    esperimenti_coinvolti=('esperimento', lambda x: sorted(x.unique())),
    gruppi_originali=('gruppo_ingrandimento', lambda x: sorted(x.unique()))
).sort_values('nm_per_pixel')

print(f"Totale classi di calibrazione reali: {df['classe_calibrazione'].nunique()}")
print(f"Totale immagini: {len(df)}\n")

for classe, row in riepilogo_classi.iterrows():
    print(f"{classe}: {row['nm_per_pixel']:.3f} nm/px, {row['n_immagini']} immagini")
    print(f"   esperimenti: {row['esperimenti_coinvolti']}")
    print(f"   etichette originali: {row['gruppi_originali']}\n")

Totale classi di calibrazione reali: 10
Totale immagini: 144

classe_1: 0.450 nm/px, 7 immagini
   esperimenti: ['28_07_26_U87WT_Immunogold_Ida']
   etichette originali: ['200nm_gruppoC']

classe_2: 0.560 nm/px, 9 immagini
   esperimenti: ['06_08_26_U87KO_Immunogold_Ida', '09_07_26_U87WT_Immunogold_Ida']
   etichette originali: ['200nm_gruppoC']

classe_3: 0.670 nm/px, 17 immagini
   esperimenti: ['06_08_26_U87KO_Immunogold_Ida', '09_07_26_U87WT_Immunogold_Ida', '28_07_26_U87WT_Immunogold_Ida']
   etichette originali: ['200nm_gruppoB']

classe_4: 0.845 nm/px, 39 immagini
   esperimenti: ['06_08_26_U87KO_Immunogold_Ida', '09_07_26_U87WT_Immunogold_Ida', '28_07_26_U87WT_Immunogold_Ida']
   etichette originali: ['200nm_gruppoA']

classe_5: 1.125 nm/px, 43 immagini
   esperimenti: ['06_08_26_U87KO_Immunogold_Ida', '09_07_26_U87WT_Immunogold_Ida', '10_07_26_U87KO_Immunogold_Ida', '28_07_26_U87WT_Immunogold_Ida']
   etichette originali: ['500nm_gruppoA', '500nm_gruppoB', '500nm_gruppoC']

classe_6: 1.405 nm/px, 6 immagini
   esperimenti: ['09_07_26_U87WT_Immunogold_Ida', '10_07_26_U87KO_Immunogold_Ida', '28_07_26_U87WT_Immunogold_Ida']
   etichette originali: ['500nm_gruppoA', '500nm_gruppoB']

classe_7: 1.680 nm/px, 17 immagini
   esperimenti: ['06_08_26_U87KO_Immunogold_Ida', '09_07_26_U87WT_Immunogold_Ida', '10_07_26_U87KO_Immunogold_Ida']
   etichette originali: ['500nm_gruppoA', '500nm_gruppoB']

classe_8: 2.110 nm/px, 2 immagini
   esperimenti: ['06_08_26_U87KO_Immunogold_Ida', '09_07_26_U87WT_Immunogold_Ida']
   etichette originali: ['1000nm_gruppoA']

classe_9: 2.820 nm/px, 2 immagini
   esperimenti: ['09_07_26_U87WT_Immunogold_Ida', '10_07_26_U87KO_Immunogold_Ida']
   etichette originali: ['1000nm_gruppoA', '1000nm_gruppoB']

classe_10: 5.630 nm/px, 2 immagini
   esperimenti: ['09_07_26_U87WT_Immunogold_Ida']
   etichette originali: ['2000nm_gruppoA']